//GIT-VS-VERSION-GEN.bat generated resource header.
#define GEN_VER_VERSION_STRING   "0.10909.2021.3.gbf51b.dirty\0" 
#define GEN_VER_DIGITAL_VERSION  0,10909,2021,3 
#define GEN_VER_VERSION_HEX      0x00002A9D07E50003 
#define GEN_VER_COMMENT_STRING   "Major Version Release\0" 
#define GEN_VER_PRIVATE_FLAG     VS_FF_PRIVATEBUILD 
#define GEN_VER_PRIVATE_STRING   "Custom Build\0" 
#define GEN_VER_PATCHED_FLAG     VS_FF_PATCHED 
#define GEN_VER_PRERELEASE_FLAG  0 
